# Generated by Django 3.0.6 on 2020-06-07 22:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosfitbit',
            name='data',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='diariodesintomas',
            name='data',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='notificacaodeatividade',
            name='data',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='dataNascimento',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.DeleteModel(
            name='Sintoma',
        ),
    ]
