# Generated by Django 3.0.6 on 2020-05-17 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default=None, max_length=200)),
                ('metaMensal', models.FloatField(default=None)),
                ('duracao', models.FloatField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Sintoma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(default=None, max_length=10000)),
                ('gravidade', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default=None, max_length=200)),
                ('idade', models.IntegerField(default=None)),
                ('peso', models.FloatField(default=None)),
                ('grauAsma', models.IntegerField(default=0)),
                ('cpf', models.CharField(default=None, max_length=11)),
                ('senha', models.CharField(default=None, max_length=15)),
                ('emEsperaDeMedico', models.BooleanField(default=False)),
                ('cadastro', models.BooleanField(default=False)),
                ('login', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrientacoesMedicas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.CharField(max_length=10000)),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='NotificacaoDeAtividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.CharField(max_length=1000)),
                ('data', models.DateField()),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='DiarioDeSintomas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Paciente')),
                ('sintomas', models.ManyToManyField(to='core.Sintoma')),
            ],
        ),
        migrations.CreateModel(
            name='DadosFitBit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batimento', models.IntegerField(default=None, max_length=3)),
                ('passos', models.IntegerField(default=None, max_length=8)),
                ('atividade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Atividade')),
            ],
        ),
        migrations.AddField(
            model_name='atividade',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Paciente'),
        ),
        migrations.CreateModel(
            name='AgenteDeSaude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default=None, max_length=200)),
                ('senha', models.CharField(default=None, max_length=15)),
                ('login', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
