# Generated by Django 3.0.6 on 2020-06-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diariodesintomas',
            name='bombinha',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='notificacaodeatividade',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='diariodesintomas',
            name='chiado',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='diariodesintomas',
            name='dormir',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='diariodesintomas',
            name='faltaDeAr',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='diariodesintomas',
            name='tosse',
            field=models.IntegerField(default=1),
        ),
    ]
