# Generated by Django 3.0.6 on 2020-06-23 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200622_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='dataRealizada',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
