# Generated by Django 3.0.6 on 2020-06-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_atividade_datarealizada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='metaMensal',
        ),
        migrations.AddField(
            model_name='atividade',
            name='intensidade',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='atividade',
            name='passos',
            field=models.IntegerField(default=None),
        ),
    ]
